### ISSUE TITLE
Database initial functionality.

### ISSUE THREAD

**Issue by astoyanow** [DiscoTrayStudios/ArkansasAssetBuildersJAVA#6]
Create initial CRUD, filter, etc. functions for initial database functionality.
- Just want to be able to get certain rows and columns from the database based on criteria.
- Create, read, update, and destroy functionality focused on first.
- Since GUI most likely won't be connected yet, can print to output.

Acceptance: database functions can return rows and columns based on filter criteria. Functions can also do CRUD operations on database as well.

**Comment by matthew-kalahiki** [comment]
done
